
var app = new Vue({
    el: '#app',
    data: {

       lista3: [],
       // dinamic string generated by select
       genreChosen: "all"
   },

   created(){
      // Reference to change the name of this in self to avoid scoping the window site in axios.get //
      const self = this;

            // calling the API with Jason //
            axios.get('https://flynn.boolean.careers/exercises/api/array/music')
            // Methods inside get //
            .then(function (response) {
                // Testing the call API made with JASON //
                console.log(response)
                // reference using response.data.response //
                 self.lista3 = response.data.response
                 // Testing //
                 console.log(self.lista3)


            })
            .catch(function (error) {
                alert(error);
            });
        },


        methods:{


             filterGenre(){
                 const self = this;
               // calling the API with Jason //
               axios.get('https://flynn.boolean.careers/exercises/api/array/music')
               // Methods inside get //
               .then(function (response) {
                   // Testing the call API made with JASON //
                   console.log(response)
                   // refenze variable default object "all" //
                   let cdslist = response.data.response;
                    // Filter appling in cds list if the value is different from "all"

                    if (self.genreChosen !== "all") {
                          cdslist = cdslist.filter(element =>{
                          // Returning only the elemnt.genre white same value in genreChosen //
                          return element.genre.toLowerCase() === self. genreChosen;
                      });

                    }
                    // Returnig the list with or withnot the filter applied //
                    self.lista3 = cdslist;

                    console.log(self.lista3)

                 })
                 .catch(function (error) {
                     alert(error);
                 });
             }
        }




});
